# stage 1

FROM ubuntu as build

WORKDIR /app

COPY requirements.txt /app/

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv pkg-config \
    libdbus-1-dev libglib2.0-dev build-essential python3-dev dbus-x11 libcairo2-dev libgirepository1.0-dev \
 && python3 -m venv /app/venv \
 && /app/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

#stage 2

FROM python:3.12-slim

WORKDIR /app

# Copy virtualenv from build stage
COPY --from=build /app/venv /app/venv
COPY --from=build /app /app

# Ensure venv python is used
ENV PATH="/app/venv/bin:$PATH"

EXPOSE 8000

CMD source venv1/bin/activate && python3 manage.py runserver 0.0.0.0:8000
